alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
alias pping="prettyping"
alias ncdu="ncdu --color off -rr -x"
alias ndu="ncdu --color off -rr -x"
alias tolower="tr '[:upper:]' '[:lower:]'"
alias toupper="tr '[:lower:]' '[:upper:]'"
alias tg="terragrunt"
alias sed-in-place="sed -i '' -e"
alias l="exa --oneline"
alias ls="exa --group-directories-first"
alias ll="exa --long --group-directories-first"
alias la="exa --long --all --group-directories-first"
alias lg="exa --long --git --group-directories-first"
alias lga="exa --long --git --all --group-directories-first"
alias lt="exa --long --all --tree --ignore-glob=.git --group-directories-first"
alias ltg="exa --long --all --tree --ignore-glob=.git --git-ignore --group-directories-first"
alias btm="btm -m"
alias b="btm"
alias h="htop"
alias p="procs --watch"
