alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
alias ls="ls --color=auto"
alias pping="prettyping"
alias ncdu="ncdu --color off -rr -x"
alias ndu="ncdu --color off -rr -x"
alias glances="glances --disable-bg"
alias tolower="tr '[:upper:]' '[:lower:]'"
alias toupper="tr '[:lower:]' '[:upper:]'"
alias tg="terragrunt"
alias l="exa --oneline"
alias ls="exa"
alias ll="exa --long --git"
alias la="exa --long --git --all"
alias lt="exa --long --git --all --tree --ignore-glob=.git"
