alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
alias pping="prettyping"
alias ncdu="ncdu --color off -rr -x"
alias ndu="ncdu --color off -rr -x"
alias tolower="tr '[:upper:]' '[:lower:]'"
alias toupper="tr '[:lower:]' '[:upper:]'"
alias tg="terragrunt"
alias sed-in-place="sed -i '' -e"
alias l="eza --oneline"
alias ls="eza --group-directories-first"
alias ll="eza --long --group-directories-first"
alias la="eza --long --all --group-directories-first"
alias lg="eza --long --git --group-directories-first"
alias lga="eza --long --git --all --group-directories-first"
alias lt="eza --long --all --tree --ignore-glob=.git --group-directories-first"
alias ltg="eza --long --all --tree --ignore-glob=.git --git-ignore --group-directories-first"
alias btm="btm -m"
alias b="btm"
alias h="htop"
alias p="procs --watch"
alias gdu="gdu-go"
alias glow="glow --pager --width 120"
alias mk="minikube"
alias kx="kubectx"
alias ax="azctx"
alias dog="doggo"
